### ISSUE TITLE
[BUG] Module contamination from late function validation

### ISSUE THREAD

**Issue by c0d1f1ed** [NVIDIA/warp#1251]
### Bug Description

Function return type validation introduced in commit 99493f4 occurs too late in the compilation pipeline, causing C++ compilation failures that contaminate entire modules when a single function has an invalid return type annotation.

When a function with an invalid return type annotation is called by a kernel:

  1. The kernel's C++ code is generated with calls to the invalid function
  2. The function validation fails during its own code generation
  3. The function's C++ code is never emitted
  4. C++ compilation fails with cryptic errors like:
  error: use of undeclared identifier 'function_name_1'
  5. All kernels in that module fail, not just the one calling the invalid function

**Comment by c0d1f1ed** [comment]
Fixed in 46944b085462ee2e9a7b799928e5c87c44f4c90d.
